# Generated by Django 3.2.9 on 2021-12-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_additionalimage_bb'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='send_messages',
            field=models.BooleanField(default=True, verbose_name='Оповещать при новых комментариях?'),
        ),
    ]
