# Generated by Django 3.2.9 on 2021-12-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_advuser_send_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='fio',
            field=models.CharField(default=True, max_length=50, verbose_name='Введите ФИО'),
        ),
    ]
