# Generated by Django 3.2.9 on 2021-12-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_advuser_fio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='additionalimage',
            name='bb',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='rubric',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='super_rubric',
        ),
        migrations.DeleteModel(
            name='SubRubric',
        ),
        migrations.DeleteModel(
            name='SuperRubric',
        ),
        migrations.DeleteModel(
            name='AdditionalImage',
        ),
        migrations.DeleteModel(
            name='Bb',
        ),
        migrations.DeleteModel(
            name='Rubric',
        ),
    ]
