# Generated by Django 3.2.9 on 2021-12-15 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211214_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.utilities.get_timestamp_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Доп иллюстрация',
                'verbose_name_plural': 'Доп иллюстрация',
            },
        ),
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=120, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Фото')),
                ('status', models.CharField(blank=True, choices=[('На обработке', 'На обработке'), ('В работе', 'В работе'), ('Выполнено', 'Выполнено')], default='Новая', max_length=120, null=True, verbose_name='status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Заявку',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='bb',
            name='category',
            field=models.ForeignKey(max_length=120, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='additionalimage',
            name='bb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bb', verbose_name='Заявки'),
        ),
    ]
