# Generated by Django 3.2.9 on 2021-12-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211215_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='category',
        ),
    ]
