# Generated by Django 3.2.11 on 2022-01-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211216_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
