# Generated by Django 3.2.11 on 2022-01-07 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.TextField(choices=[('3D Дизайн', '3D Дизайн'), ('2D Дизайн', '2D Дизайн'), ('Эскиз', 'Эскиз')], verbose_name='Категория')),
                ('status', models.TextField(choices=[('Новый', 'Новый'), ('Принято в работу', 'Принято в работу'), ('Выполнено', 'Выполнено')], default='Новый', verbose_name='Статус заявки')),
                ('image', models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор объявления')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
