# Generated by Django 4.0.3 on 2022-04-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_posts_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.TextField(max_length=100, verbose_name='Описание'),
        ),
    ]
