# Generated by Django 4.0.3 on 2022-04-26 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_category',
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(max_length=120, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория'),
        ),
    ]
