# Generated by Django 4.0.3 on 2022-04-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_name_category_name_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.TextField(choices=[('3D Дизайн', '3D Дизайн'), ('2D Дизайн', '2D Дизайн'), ('Эскиз', 'Эскиз')], verbose_name='Категория'),
        ),
    ]
