# Generated by Django 4.0.3 on 2022-04-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_category_options_remove_category_name_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='send_messages',
            field=models.BooleanField(default=True, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='fio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО'),
        ),
    ]
