# Generated by Django 4.0.3 on 2022-05-06 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_advuser_send_messages_alter_advuser_fio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(max_length=120, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.TextField(choices=[('Новый', 'Новый'), ('Принято в работу', 'Принято в работу'), ('Выполнено', 'Выполнено'), ('Отменено', 'Отменено')], default='Новый', verbose_name='Статус заявки'),
        ),
    ]
