# Generated by Django 4.0.3 on 2022-05-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_posts_cancellation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='cancellation',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Введите если отменяете заказ'),
        ),
    ]
